# Generated by Django 5.2.5 on 2025-08-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("extracted_text", models.TextField()),
                ("identified_concepts", models.JSONField(default=list)),
                ("extracted_equations", models.JSONField(default=list)),
                ("concept_embeddings", models.JSONField(default=list)),
                ("recommended_courses", models.JSONField(default=list)),
                ("confidence_scores", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConceptEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(unique=True)),
                ("embedding_scibert", models.JSONField()),
                ("embedding_mathbert", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PhysicsConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField()),
                ("embedding", models.JSONField(null=True)),
                ("field", models.CharField(max_length=100)),
                ("difficulty_level", models.IntegerField(default=1)),
                ("example_equations", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="MITCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_number", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("syllabus", models.TextField(null=True)),
                ("url", models.URLField()),
                ("department", models.CharField(max_length=100)),
                ("level", models.CharField(max_length=50)),
                ("title_embedding", models.JSONField(null=True)),
                ("description_embedding", models.JSONField(null=True)),
                ("syllabus_embedding", models.JSONField(null=True)),
                ("topics_covered", models.JSONField(default=list)),
                ("equations_covered", models.JSONField(default=list)),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        related_name="required_for", to="api.mitcourse"
                    ),
                ),
                (
                    "concepts",
                    models.ManyToManyField(
                        related_name="courses", to="api.physicsconcept"
                    ),
                ),
            ],
        ),
    ]
